# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('item_unique', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sold', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, max_length=7)),
            ],
        ),
    ]
